steps:
- name: 'python:3.10'
  entrypoint: bash
  args:
    - '-c'
    - |
      pip install -r requirements.txt -t .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/telegram-media-bot:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/telegram-media-bot:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - '-c'
    - |
      gcloud run deploy telegram-media-bot \
        --image gcr.io/$PROJECT_ID/telegram-media-bot:$SHORT_SHA \
        --region asia-south1 \
        --platform managed \
        --allow-unauthenticated \
        --set-env-vars TELEGRAM_BOT_TOKEN=$$TELEGRAM_BOT_TOKEN
